# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
PS1="[\[\e[0;32m\]\u@\h] (\[\e[00;35m\]\d - \t\[\e[00m\])\n\w \$ "

#Set GREP_COLOR to default red
alias grep='grep --color=auto'
alias ext='. ext'
alias psql='psql -U postgres'